use std::io::Write;

use anyhow::{Context, Result};
use globset::{GlobBuilder, GlobSet, GlobSetBuilder};
use serde::{Deserialize, Serialize};

use crate::Report;

/// Analysis/CI settings only; input and output paths stay explicit CLI arguments.
#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase", deny_unknown_fields)]
pub struct Config {
    pub include: Vec<String>,
    pub exclude: Vec<String>,
    pub compression: bool,
    pub budgets: Budgets,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase", deny_unknown_fields)]
pub struct Budgets {
    pub max_bytes: Option<usize>,
    pub max_unobserved_bytes: Option<usize>,
    pub max_unmeasured_bytes: Option<usize>,
    pub max_gzip_bytes: Option<usize>,
    pub max_brotli_bytes: Option<usize>,
}

impl Budgets {
    pub fn check(&self, report: &Report) -> Vec<String> {
        let compressed = report.compression.as_ref();
        let mut failures = Vec::new();
        for (label, limit, value) in [
            ("generated bytes", self.max_bytes, Some(report.totals.bytes)),
            (
                "unobserved bytes",
                self.max_unobserved_bytes,
                Some(report.totals.unobserved_bytes),
            ),
            (
                "unmeasured bytes",
                self.max_unmeasured_bytes,
                Some(report.totals.unmeasured_bytes),
            ),
            (
                "gzip bytes",
                self.max_gzip_bytes,
                compressed.map(|c| c.gzip_bytes),
            ),
            (
                "Brotli bytes",
                self.max_brotli_bytes,
                compressed.map(|c| c.brotli_bytes),
            ),
        ] {
            if let Some(limit) = limit {
                match value {
                    Some(value) if value > limit => {
                        failures.push(format!("{label}: {value} exceeds budget {limit}"))
                    }
                    None => {
                        failures.push(format!("{label}: cannot check budget without compression"))
                    }
                    _ => {}
                }
            }
        }
        failures
    }
}

pub fn globs(patterns: &[String]) -> Result<GlobSet> {
    let mut builder = GlobSetBuilder::new();
    for pattern in patterns {
        builder.add(
            GlobBuilder::new(pattern)
                .literal_separator(true)
                .build()
                .with_context(|| format!("invalid bundle glob {pattern:?}"))?,
        );
    }
    Ok(builder.build()?)
}

#[derive(Debug, Default, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CompressedSizes {
    /// Independent file compression, gzip level 6 and Brotli quality 5 / lgwin 22.
    pub gzip_bytes: usize,
    pub brotli_bytes: usize,
}

pub fn compress(data: &[u8]) -> Result<CompressedSizes> {
    let (gzip, brotli) = compressed_streams(data)?;
    Ok(CompressedSizes {
        gzip_bytes: gzip.len(),
        brotli_bytes: brotli.len(),
    })
}

pub(crate) fn gzip(data: &[u8]) -> Result<Vec<u8>> {
    let mut gzip = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::new(6));
    gzip.write_all(data)?;
    Ok(gzip.finish()?)
}

fn compressed_streams(data: &[u8]) -> Result<(Vec<u8>, Vec<u8>)> {
    let gzip = gzip(data)?;
    let mut encoded = Vec::new();
    {
        let mut brotli = brotli::CompressorWriter::new(&mut encoded, 4096, 5, 22);
        brotli.write_all(data)?;
    }
    Ok((gzip, encoded))
}

pub fn markdown(report: &Report) -> String {
    let mut out = format!(
        "# bundle-trace\n\nGenerated UTF-8 bytes: **{}** across {} selected bundles.\n\n| Observed | Unobserved | Unmeasured |\n| ---: | ---: | ---: |\n| {} B | {} B | {} B |\n\nUnobserved means not executed during the supplied scenarios, not safe to delete.\n",
        report.totals.bytes,
        report.bundles.len(),
        report.totals.observed_bytes,
        report.totals.unobserved_bytes,
        report.totals.unmeasured_bytes
    );
    if let Some(c) = &report.compression {
        out.push_str(&format!("\nSum of independently compressed bundles: gzip (level 6) **{} B**, Brotli (quality 5, lgwin 22) **{} B**. These are not estimates of removable bytes or actual server encoding.\n", c.gzip_bytes, c.brotli_bytes));
    }
    out.push_str(&format!("\n{} bundles excluded by CLI/config filters; totals and budgets use selected bundles only.\n\n| Package | Generated B | Unobserved B | Unmeasured B |\n| --- | ---: | ---: | ---: |\n", report.excluded_bundles.len()));
    for row in report.packages.iter().take(20) {
        out.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            escape_markdown(&row.package),
            row.counts.bytes,
            row.counts.unobserved_bytes,
            row.counts.unmeasured_bytes
        ));
    }
    out.push_str(&format!("\n{} analysis warnings.\n", report.warnings.len()));
    for failure in &report.budget_failures {
        out.push_str(&format!(
            "\n- Budget failed: {}\n",
            escape_markdown(failure)
        ));
    }
    out
}

fn escape_markdown(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('|', "&#124;")
        .replace(['\r', '\n'], " ")
        .replace('`', "&#96;")
        .replace('[', "&#91;")
        .replace(']', "&#93;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Read;

    #[test]
    fn compressed_streams_round_trip_and_report_actual_lengths() {
        for data in [
            Vec::new(),
            "한🔥".repeat(100).into_bytes(),
            include_bytes!("../examples/recorded/entry.js").to_vec(),
        ] {
            let (gzip, brotli) = compressed_streams(&data).unwrap();
            let mut inflated = Vec::new();
            flate2::read::GzDecoder::new(gzip.as_slice())
                .read_to_end(&mut inflated)
                .unwrap();
            assert_eq!(inflated, data);
            inflated.clear();
            brotli::Decompressor::new(brotli.as_slice(), 4096)
                .read_to_end(&mut inflated)
                .unwrap();
            assert_eq!(inflated, data);
            let sizes = compress(&data).unwrap();
            assert_eq!(sizes.gzip_bytes, gzip.len());
            assert_eq!(sizes.brotli_bytes, brotli.len());
        }
    }
}
