use std::fs;
use std::path::PathBuf;

use anyhow::{Context, Result, ensure};
use clap::Parser;

#[derive(Parser)]
#[command(
    version,
    about = "Trace generated JavaScript bytes to sources; import V8/DevTools coverage and export offline reports"
)]
struct Args {
    /// Recursively scan JS files, local sourceMappingURL maps or adjacent .map files.
    #[arg(long)]
    dir: PathBuf,
    /// Repeat for multiple scenarios. Observed ranges are unioned, not summed.
    #[arg(long)]
    coverage: Vec<PathBuf>,
    /// Optional esbuild metafile for import paths (not inferred from source maps).
    #[arg(long)]
    metafile: Option<PathBuf>,
    /// Write source/bundle totals. Use --details to include code and ranges.
    #[arg(long)]
    json: Option<PathBuf>,
    /// Include generated/original code and all mapping intervals in JSON (can be large).
    #[arg(long)]
    details: bool,
    /// Write a self-contained interactive HTML report (includes source code).
    #[arg(long)]
    html: Option<PathBuf>,
    /// Strip this URL prefix to obtain a path under --dir. Repeatable; end with /.
    #[arg(long)]
    url_prefix: Vec<String>,
    /// JSON object mapping exact coverage URLs to relative bundle paths.
    #[arg(long)]
    script_map: Option<PathBuf>,
    /// Explicit bundle-relative-path=map-file binding. Repeatable; permits maps outside --dir.
    #[arg(long = "map")]
    maps: Vec<String>,
    /// Permit raw V8 inputs without captured source text/hash; mark them unverified.
    #[arg(long)]
    allow_unverified: bool,
    /// JSON config for include/exclude, compression, and budgets.
    #[arg(long)]
    config: Option<PathBuf>,
    /// Include bundle-relative glob (repeatable); * does not cross /.
    #[arg(long)]
    include: Vec<String>,
    /// Exclude bundle-relative glob (repeatable); takes precedence over include.
    #[arg(long)]
    exclude: Vec<String>,
    /// Calculate whole-file gzip (level 6) and Brotli (quality 5) sizes.
    #[arg(long)]
    compression: bool,
    /// Write a Markdown summary for CI artifacts.
    #[arg(long)]
    markdown: Option<PathBuf>,
    /// Fail with exit code 2 when selected generated bytes exceed this budget.
    #[arg(long)]
    max_bytes: Option<usize>,
    /// Fail when unobserved bytes exceed this budget. Does not include unmeasured bytes.
    #[arg(long)]
    max_unobserved_bytes: Option<usize>,
    /// Fail when unmeasured bytes exceed this budget.
    #[arg(long)]
    max_unmeasured_bytes: Option<usize>,
    /// Print an import path to this exact esbuild input key.
    #[arg(long, requires = "metafile")]
    why: Option<String>,
    #[arg(long, default_value_t = 20)]
    limit: usize,
}

fn main() -> Result<()> {
    let args = Args::parse();
    let mut config: bundle_trace::ci::Config = if let Some(path) = &args.config {
        serde_json::from_slice(&fs::read(path)?).context("invalid --config")?
    } else {
        Default::default()
    };
    let mut options = bundle_trace::AnalyzeOptions {
        include: config.include,
        exclude: config.exclude,
        details: args.details || args.html.is_some(),
        ..Default::default()
    };
    options.include.extend(args.include);
    options.exclude.extend(args.exclude);
    options.compression = config.compression
        || args.compression
        || config.budgets.max_gzip_bytes.is_some()
        || config.budgets.max_brotli_bytes.is_some();
    config.budgets.max_bytes = args.max_bytes.or(config.budgets.max_bytes);
    config.budgets.max_unobserved_bytes = args
        .max_unobserved_bytes
        .or(config.budgets.max_unobserved_bytes);
    config.budgets.max_unmeasured_bytes = args
        .max_unmeasured_bytes
        .or(config.budgets.max_unmeasured_bytes);
    options.input.url_prefixes = args.url_prefix;
    options.input.allow_unverified = args.allow_unverified;
    if let Some(path) = args.script_map {
        options.input.script_paths = serde_json::from_slice(&fs::read(path)?)
            .context("--script-map must be an object mapping URLs to relative paths")?;
    }
    for binding in args.maps {
        let (bundle, map) = binding
            .split_once('=')
            .context("--map must be bundle-relative-path=map-file")?;
        ensure!(!map.is_empty(), "--map needs a map file path");
        ensure!(
            options.maps.insert(bundle.into(), map.into()).is_none(),
            "duplicate --map for {bundle}"
        );
    }
    let mut report = bundle_trace::analyze_with_options(&args.dir, &args.coverage, &options)?;
    report.budget_failures = config.budgets.check(&report);
    if let Some(path) = args.metafile {
        report.import_paths = Some(bundle_trace::metadata::import_paths(&fs::read(path)?)?);
    }
    println!(
        "Generated UTF-8 bytes: {} ({} bundles)",
        report.totals.bytes,
        report.bundles.len()
    );
    println!(
        "Observed: {} | Unobserved: {} | Unmeasured: {}",
        report.totals.observed_bytes,
        report.totals.unobserved_bytes,
        report.totals.unmeasured_bytes
    );
    println!("Unobserved means not executed during the supplied scenarios, not safe to delete.\n");
    if !report.excluded_bundles.is_empty() {
        println!(
            "{} bundles excluded; totals and budgets use selected bundles only.\n",
            report.excluded_bundles.len()
        );
    }
    if let Some(compression) = &report.compression {
        println!(
            "Whole-file compression sum: gzip {} B | Brotli {} B\n",
            compression.gzip_bytes, compression.brotli_bytes
        );
    }
    println!(
        "{:>12} {:>12} {:>12} {:>12}  Package",
        "Bytes", "Observed", "Unobserved", "Unmeasured"
    );
    let mut packages = report.packages.iter().collect::<Vec<_>>();
    if !args.coverage.is_empty() {
        packages.sort_by(|a, b| {
            b.counts
                .unobserved_bytes
                .cmp(&a.counts.unobserved_bytes)
                .then(a.package.cmp(&b.package))
        });
    }
    for row in packages.into_iter().take(args.limit) {
        println!(
            "{:>12} {:>12} {:>12} {:>12}  {}",
            row.counts.bytes,
            row.counts.observed_bytes,
            row.counts.unobserved_bytes,
            row.counts.unmeasured_bytes,
            row.package
        );
    }
    if let Some(source) = args.why {
        let row = report
            .import_paths
            .as_ref()
            .unwrap()
            .iter()
            .find(|row| row.source == source)
            .ok_or_else(|| {
                anyhow::anyhow!("no emitted contribution for metafile input {source}")
            })?;
        println!(
            "\nImport path ({} metafile bytes): {}",
            row.bytes_in_output,
            row.path
                .as_ref()
                .map(|path| path.join(" -> "))
                .unwrap_or("[unknown]".into())
        );
    }
    for warning in &report.warnings {
        eprintln!("warning: {warning}");
    }
    if let Some(path) = args.html {
        write_report(path, bundle_trace::report::html(&report)?)?;
    }
    if !args.details {
        report.strip_details();
    }
    if let Some(path) = args.json {
        write_report(path, serde_json::to_string(&report)? + "\n")?;
    }
    if let Some(path) = args.markdown {
        write_report(path, bundle_trace::ci::markdown(&report))?;
    }
    if !report.budget_failures.is_empty() {
        for failure in &report.budget_failures {
            eprintln!("budget failed: {failure}");
        }
        std::process::exit(2);
    }
    Ok(())
}

fn write_report(path: PathBuf, content: String) -> Result<()> {
    if let Some(parent) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}
